repos:
  - repo: https://github.com/ambv/black
    rev: 23.3.0
    hooks:
      - id: black
        exclude: >
          (?x)^(
            scripts/gen-docs-index|
          )$

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.2.3
    hooks:
      - id: check-ast
      - id: check-json
      - id: check-merge-conflict
      - id: check-yaml
        exclude: deploy/
      - id: debug-statements
      - id: detect-private-key
      - id: fix-encoding-pragma
      - id: flake8
      - id: trailing-whitespace

  - repo: https://github.com/igorshubovych/markdownlint-cli
    rev: v0.17.0
    hooks:
      - id: markdownlint
        entry: markdownlint --ignore .github/*.md

  - repo: https://github.com/aws-cloudformation/cfn-python-lint
    rev: v0.77.3
    hooks:
      - id: cfn-python-lint
        files: deploy/
