#! /usr/bin/env bash

set -eu -o pipefail

#
# Run the update.lambda_handler locally in a docker container
#

rm -rf tmp/
unzip -qq -d ./tmp build/lambda.zip

NAME="antivirus-update"

docker run --rm \
  -v "$(pwd)/tmp/:/var/task" \
  -e AV_DEFINITION_PATH \
  -e AV_DEFINITION_S3_BUCKET \
  -e AV_DEFINITION_S3_PREFIX \
  -e AWS_ACCESS_KEY_ID \
  -e AWS_DEFAULT_REGION \
  -e AWS_REGION \
  -e AWS_SECRET_ACCESS_KEY \
  -e AWS_SESSION_TOKEN \
  -e CLAMAVLIB_PATH \
  --memory="${MEM}" \
  --memory-swap="${MEM}" \
  --cpus="${CPUS}" \
  --name="${NAME}" \
  lambci/lambda:python3.8 update.lambda_handler
